# Dockerfile.lambda
# python3.11のイメージをダウンロード
FROM public.ecr.aws/lambda/python:3.11

# pythonの出力表示をDocker用に調整
ENV PYTHONUNBUFFERED=1

WORKDIR /var/task

# 必要なライブラリをインストール
COPY requirements.txt ./
RUN pip install -r requirements.txt

# FastAPIアプリケーションのコードをコピー
COPY . .

# Lambdaのエントリーポイントを設定
CMD ["lambda_handler.handler"]